query ($device_name: [String]) {
  devices(name: $device_name) {
    id
    name
    role { name }
    location { name }
    platform { name network_driver }
    primary_ip4 { address }
    config_context
    interfaces {
      name
      description
      enabled
      mode
      ip_addresses { address }
      untagged_vlan { vid name }
      tagged_vlans { vid name }
    }
  }
}
